---
title: "'Step into the Spotlight'- A Look into the Media Strand of Creative Europe"
format: html
editor: visual
---

## But first... what is Creative Europe?

**Creative Europe** is a branch of the European Union's policy on 'culture'. Enshrined under Article 167 of the Treaty of the Functioning of the European Union, **Creative Europe** seeks to help Member States solve common problems related to the creative and cultural sectors. Other initiatives include:

-   European Capitals of Culture

-   European Union Prizes for cultural sectors

-   European Heritage Days

### The Main Goal of Creative Europe

is to "safeguard, develop, and promote European cultural and linguistic diversity and heritage" and to "increase the competitiveness and the economic potential of the cultural and creative sectors" (Creative Europe).

In other words, the main goal of this program is to support policies from the Member States that encourages pluralism, cross-border cooperation and networking activities for all culture and creative sectors through the European Union. Though there is no real consensus of what *exactly* sectors make up 'creative and cultural industries', they are generally "those industries which have their origin in individual creativity, skill and talent and which have a potential for wealth and job creation through the generation and exploitation of intellectual property" (Department for Culture, Media and Sport). These include:

1.  Advertising

2.  Architecture

3.  The Art and Antiques Market

4.  Crafts

5.  Design

6.  Designer Fashion

7.  Film and Video

8.  Interactive Leisure Software

9.  Music

10. The Performing Arts

11. Publishing

12. Software and Computer Games

13. Television and Radio

Though Creative Europe addresses many of the aforementioned sectors, the Media strand of Creative Europe is specifically designed to **support policies relating to Europe's film and audiovisual sector**. To explore more, click on the following links below!

[**Fundamentals of the Media Strand of Creative Europe**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/FundamentalsoftheMediaStrandofCreativeEurope.html)

[**The Direct Benefits to Artists/ Creatives, Businesses, and the Every Day Individual**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/TheDirectBenefitstoArtistsCreativesBusinessesandtheEveryDayIndividual.qmd)

[**The Film and Audiovisual Industry as an Avenue for Social Cohesion**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/TheFilmandAudiovisualIndustryasanAvenueforSocialCohesion.html)

[**Who *really* cares though?**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/WhoReallyCaresThough.html)

Works Cited

“Creative Europe \| EUR-Lex.” https://eur-lex.europa.eu/EN/legal-content/summary/creative-europe.html (December 11, 2024).

“Department for Culture, Media and Sport.” 2024. *GOV.UK*. https://www.gov.uk/government/organisations/department-for-culture-media-and-sport (December 11, 2024).
