---
title: "The Film and Audiovisual Industry as an Avenue for Social Cohesion"
format: html
editor: visual
---

## The Role of Film and Audiovisual Media in the Maintenance of Social Cohesion

The links between social cohesion and the film and audiovisual sector are vast but difficult to represent through data or visualizations. Despite that though, it is still ever important to describe the role it plays in the promotion and maintenance of social cohesion. In very broad terms, creatives and artists in the film and audiovisual sector create cultural products, such as films, TV shows, online media, and video games, that shape social interactions, identities, and collective values. In recent years, it has become clear that audiovisual media possess the potential to promote social disunity and social fragmentation. However, this negative effect can be mitigated through careful and considerate actions that harness the sector's ability to promote shared values and identity and foster empathy and understanding. This is not to say that we should be limiting artists and creatives in their ability to produce certain works, especially if they may be more provocative in nature. Rather, the industry needs help to support the appropriate avenues that facilitate discussions and dialogue about the impact that audiovisual media may or may not have on the broader public. Examples of these avenues include national and international film festivals, like the Berlin International Film Festival or Cannes Film Festival. Not only do these festivals promote dialogue, but they actively allow for a diverse group of filmmakers to attract a wider audience outside of their domestic or national markets. While these festivals are not usually meant for the wider general public and typically reserved for industry professionals, they do allow for limited attendance from the public. Though this limited attendance is not perfect, I argue that the digital transformation of the industry could allow for opportunities to expand the general public's access to the appropriate channels for continued and meaningful conversations that can encourage social inclusion.

[**Back to Home**](/Users/zariajohnson/Documents/POSC644/Final%20Policy%20Website/StepintotheSpotlight_ALookintotheMediaStrandofCreativeEurope.html)

[**Fundamentals of the Media Strand of Creative Europe**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/FundamentalsoftheMediaStrandofCreativeEurope.html)

[**The Direct Benefits to Artists/ Creatives, Businesses, and the Every Day Individual**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/TheDirectBenefitstoArtistsCreativesBusinessesandtheEveryDayIndividual.html)

[**The Film and Audiovisual Industry as an Avenue for Social Cohesion**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/TheFilmandAudiovisualIndustryasanAvenueforSocialCohesion.html)

[**Who really cares though?**](/Users/zariajohnson/Documents/POSC644/Final Policy Website/WhoReallyCaresThough.html)

“Audience Cluster - Culture and Creativity.” https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand/audience-cluster (December 11, 2024).

“Business Cluster - Culture and Creativity.” https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand/business-cluster (December 11, 2024).

“Content Cluster - Culture and Creativity.” https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand/content-cluster (December 11, 2024).

“Creative Europe \| EUR-Lex.” https://eur-lex.europa.eu/EN/legal-content/summary/creative-europe.html (December 11, 2024).

“Creative Europe MEDIA Strand - Culture and Creativity.” https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand (December 11, 2024).

“Department for Culture, Media and Sport.” 2024. *GOV.UK*. https://www.gov.uk/government/organisations/department-for-culture-media-and-sport (December 11, 2024).

“EU Film Industry: Market Share by Country of Origin.” *Statista*. https://www.statista.com/statistics/572603/film-industry-market-share-by-country-of-origin-eu/ (December 11, 2024).

“Eurobarometer.” https://europa.eu/eurobarometer/screen/home (December 11, 2024).

“Home - Eurostat.” https://ec.europa.eu/eurostat/en/ (December 11, 2024).

“Policy Support Cluster - Culture and Creativity.” https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand/policy-support-cluster (December 11, 2024).

“UIS Statistics.” https://data.uis.unesco.org/# (December 11, 2024).
